version: 6.1.0.{build}

branches:
  only:
  - cpp_master

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      cpp11: -DMSGPACK_CXX11=OFF
      msvc: '"Visual Studio 12 2013"'
      boost_prefix: C:\Libraries\boost_1_58_0
      boost_subdir: lib32-msvc-12.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cpp11: -DMSGPACK_CXX11=OFF
      msvc: '"Visual Studio 14 2015"'
      boost_prefix: C:\Libraries\boost_1_69_0
      boost_subdir: lib32-msvc-14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      cpp11: -DMSGPACK_CXX11=ON
      msvc: '"Visual Studio 14 2015"'
      boost_prefix: C:\Libraries\boost_1_69_0
      boost_subdir: lib32-msvc-14.0
build_script:
  - ps: |
      appveyor DownloadFile http://zlib.net/zlib-1.2.13.tar.gz -FileName zlib-1.2.13.tar.gz
      7z x zlib-1.2.13.tar.gz 2> $null
      7z x zlib-1.2.13.tar 2> $null
      cd zlib-1.2.13

      md build
      md prefix
      cd build

      cmake `
          -G $env:msvc `
          -D CMAKE_INSTALL_PREFIX="$env:APPVEYOR_BUILD_FOLDER\zlib-1.2.13\prefix" `
          ..
      if ($LastExitCode -ne 0) { exit $LastExitCode }

      cmake --build . --target install --config Release
      if ($LastExitCode -ne 0) { exit $LastExitCode }
      cd ..\..

      md build
      md prefix
      cd build

      cmake `
          -G $env:msvc `
          $env:cpp11 `
          -D MSGPACK_BUILD_EXAMPLES=ON `
          -D MSGPACK_BUILD_TESTS=ON `
          -D CMAKE_EXE_LINKER_FLAGS=/LIBPATH:"$env:boost_prefix\$env:boost_subdir" `
          -D CMAKE_PREFIX_PATH="$env:boost_prefix;$env:APPVEYOR_BUILD_FOLDER\zlib-1.2.13\prefix" `
          -D CMAKE_INSTALL_PREFIX="$env:APPVEYOR_BUILD_FOLDER\prefix" `
          -D CMAKE_CXX_FLAGS="/D_VARIADIC_MAX=10 /EHsc /DBOOST_ALL_DYN_LINK" `
          ..
      if ($LastExitCode -ne 0) { exit $LastExitCode }

      cmake --build . --config Release
      if ($LastExitCode -ne 0) { exit $LastExitCode }

test_script:
- set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%\zlib-1.2.13\build\Release;%APPVEYOR_BUILD_FOLDER%\build\release;%boost_prefix%\%boost_subdir%
- ctest -VV -C Release
